### ISSUE TITLE
incorrect version coming from previous check

### ISSUE THREAD

**Issue by smarth55** [Masquerade-Circus/mongoose-history-plugin#5]
When sorting by version doesn't work for versions past 10 because it is doing a string comparison. So version '9.0.0' is being picked up before '10.0.0'.

Having a special comparison version field that would store the semver as a number or padded int would work, but you could easily sort by `pluginOptions.timestampFieldName` as well.

**Comment by smarth55** [comment]
No, this is happening within the plugin. There are at least 3 lines where there is sorting happening on the version which is stored as a string so when building the diffs objects and getting the previous, they are being compared to the wrong version.

Handling sorting within the plugin on the timestamp field should always work, or sort using the semver package, but you can't do that in a mongo query.

**Comment by Evertvdw** [comment]
Hmm yes I see, I'm also running in trouble using this package, probably for the same reason. New versions are not being created after a 9 version. So it will get stuck at 0.9.0, I see there is a 0.10.0 created but this is not returned as the latest version probably due to the same sorting issue.

**Comment by Evertvdw** [comment]
@Masquerade-Circus I created a PR fixing this issue, could you take a look at that?

**Comment by Masquerade-Circus** [comment]
This fix is alive in https://github.com/Masquerade-Circus/mongoose-history-plugin/releases/tag/v1.6.1

Awesom work and catch @Evertvdw @smarth55.

**Comment by Evertvdw** [comment]
Thanks for picking this up so quickly!
